### PR TITLE
Example: Build the test archive (.war) during test

### PR DESCRIPTION
**Pull request by rmpestano**

### CODE REVIEW

**Comment by tandraschko** [comment]
Does IT really need guava?

**Comment by rmpestano** [comment]
I'm getting a `method not found exception` without It, I guess graphene needs a newer guava then the one provided by Selenium.

**Comment by tandraschko** [comment]
And the shrinkwrap depedency is Not required in the example, the lib already includes it

**Comment by rmpestano** [comment]
The lib doesn't include embedded maven, should we add it even if doesn't use it?

**Comment by tandraschko** [comment]
Not sure but
shrinkwrap-resolver-impl-maven
is already included in the lib, which is ok as it's often used.

Why do we need EmbeddedMaven? I worked without it and just with the maven resolver thing.

**Comment by rmpestano** [comment]
Embedded is used to build the project in @Deploymenent, see here:

https://github.com/primefaces-extensions/primefaces-arquillian/commit/6d008fbbd532fcb88645a0f61ecea6c5ad339e8e#diff-5532bc72bb230fc8076a3b07246a4724R34

**Comment by tandraschko** [comment]
I always did it with (just an example from usage, found on google)
Maven.resolver().resolve("G:A:war:V").withTransitivity().asFile();
which is delivered by
shrinkwrap-resolver-impl-maven

Whats the benefit of "EmbeddedMaven"?

**Comment by rmpestano** [comment]
- clone https://github.com/rmpestano/primefaces-arquillian/ -b build-test-archive

- cd into example test

- mvn test

I think you'll get the benefits

**Comment by tandraschko** [comment]
Not sure. Whats the benefit of using a another mvn version as the current running one?

**Comment by rmpestano** [comment]
In fact it is the current one because in @deployment we build and install PrimeFaceArquillian and build the example project using the recent installed version.

**Comment by rmpestano** [comment]
If you are talking about the maven version enforced by EmbbededMaven, you can configure it to use current installed version but I prefer to use an specific version so everyone uses the same setup (at least for maven version)

**Comment by rmpestano** [comment]
The biggest advantage here (as I talked in issue #1) is that we don't need to install PrimeFacesArquillian and build the example project to finally be able to run the tests. Everything is done in @Deployment using EmbbededMaven.

**Comment by tandraschko** [comment]
Ahh, i see

it uses maven to build the lib before and the war, inside the current build

IMO we can skip that auto-build of the lib before as it's just a example for the users and the lib will be in their maven repo already

I can post the code tomorrow, how we do it
It uses the maven-resolver to resolve the dependencies of the project and and build the WAR via ShrinkWrap.create(WebArchive.class, archiveName + ".war")
It's bit easier without downloading maven etc.

**Comment by rmpestano** [comment]
I see, what Im proposing is a (automatic)way to test the lib, that's why I commented on the other issue if you were using the sample project to verify the quality of the lib.

Suppose you add growl component to the lib and then an example in the sample project. With the proposed approach you can verify (test) the new growl component without installing or building any project, just with `mvn test` and it will install current version of the lib and use it on the test. 

Also that's why I proposed to run tests on travisci so on each change (commit) we can immediatly see if it breaks any component.

**Comment by tandraschko** [comment]
yep but thats something completely different as the example

a unittest for the lib would be e.g.
- call SelectOneMenu#toggle
- assert via selector, if the the dropdown is really visible

**Comment by rmpestano** [comment]
Sure, that's a matter of creating the tests and the assertions.

But I'm ok if you don't buy the idea. IMO it really pays on the long run to have an autommated suite for the lib (even if It is a ftest utility lib).

**Comment by tandraschko** [comment]
nono, we can do that. I just don't have time to work on that.
If you would like to work on it, i would rework the repo a little bit tomorrow:
/primefaces-arquillian
/primefaces-arquillian-example
/primefaces-arquillian-tests

"tests" would be this topic then

**Comment by rmpestano** [comment]
Ok, I'll wait the refactoring and do another PR.

**Comment by tandraschko** [comment]
refactored it
also added the whole shrinkwrap to the lib itself and switched to embeddedMaven on the example

**Pull request closed without merging**
