### PR TITLE
Add checkstyle and PMD setup to build

### PR DESCRIPTION
**Pull request by krichter722**
Most of the code already fulfills the suggested requirements. This should avoid the need for all these tiny "remove spaces" and "cosmetic" commits as well.

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
Big -1 for pmd
Also i dont like the Changes to remove Abstract etc

**Comment by tandraschko** [comment]
Also "Else" in new line is used by PF and WE should so it the Same way

**Comment by tandraschko** [comment]
added checkstyle and skipped PMD for now

i never liked to strict PMD and to strict checkstyle as it leads to @SupressWarnings
Review > PMD
we can discuss it later.

**Comment by krichter722** [comment]
Agreed. I extracted the non-controversial changes regarding PMD into #12. We can discuss them there separately.

**Pull request closed without merging**
